### ISSUE TITLE
Issue connecting to docker image

### ISSUE THREAD

**Issue by colts183281** [apmoore1/TweeboParserDocker#1]
Hi Andrew,

I'm currently getting this error code:

(ConnectionError(MaxRetryError("HTTPConnectionPool(host='0.0.0.0', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000221D5E9FB70>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context'))")), '0.0.0.0', 8000)
Error caused by Connection Error. This is most likely due to the server not running at 0.0.0.0:8000.

I get that this means it has to do with docker being set correctly (host = 0.0.0.0 and port = 8000) but I believe that it is. Here is a screen shot of my docker desktop app:

![Screenshot (2)](https://user-images.githubusercontent.com/47045579/94624188-dd32d700-0283-11eb-8ecb-ad3b1982a2f0.png)

Do you have any idea for next steps in regards to trouble shooting? I've been searching around for a couple hours but can't seem to get a good lead. Any help would be greatly appreciated!

Tyler

**Comment by apmoore1** [comment]
Hi Tyler,

Sorry about the problem. I checked this morning and it is running ok on my Ubuntu 16.0.4 machine. I think it might be a Windows problem and I have never tested it on Windows before.

One guess could be that Windows does not like Docker binding to an external IP address e.g. 0.0.0.0 thus when running docker try:
``` bash
docker run -p 127.0.0.1:8000:8000 --rm mooreap/tweeboparserdocker
```
Even though it will come up with:
```
INFO: Serving on: 0.0.0.0:8000
```
If you perform `docker ps -a` it should show that docker is actually using `127.0.0.1:8000->8000/tcp`

Then if you are running [tweebo_parser_python_api](https://github.com/apmoore1/tweebo_parser_python_api) the following code should work:
``` python
from tweebo_parser import API
tweebo_api = API(hostname='127.0.0.1')
text = ['the dog jumped over the moon', 'some example text']
result_conll = tweebo_api.parse_conll(text)
print(result_conll)
```

Best,

Andrew.

**Comment by colts183281** [comment]
Hi Andrew, 

Wow, thank you so much! That worked perfectly! Thank you so much for the quick response.

Best,
Tyler
